apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  template:
    spec:
      containers:
        - name: petclinic
          image: ghcr.io/tk-hap/k8s-demo-app:5f279b4