apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment.yaml
  - path: version.yaml
  - path: hostname.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: petclinic-ingress