apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 3 
  template:
    spec:
      containers:
      - name: petclinic
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "300m"
            memory: "500Mi"