name: CI - Build Image & Push to Dev

on:
  push:
    branches:
      - main
    paths-ignore: # Avoid loops on version bumps and non-image areas
      - '.github/workflows/**'
      - 'k8s/**'
  workflow_dispatch:

permissions:
  contents: write      # needed to commit version.yaml update
  packages: write      # push to GHCR
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/petclinic
          tags: |
             type=sha,format=short,prefix=

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update dev version.yaml with new image tag
        if: github.ref == 'refs/heads/main'
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ steps.meta.outputs.tags}}"' 'k8s/app/envs/dev/version.yaml'

      - name: Commit version bump
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update dev image to ${{ steps.meta.outputs.tags}}"
          file_pattern: k8s/app/envs/dev/version.yaml
          branch: main

      - name: Summary
        run: |
          echo "Image tags produced:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta.outputs.tags }}' | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          echo "Dev version.yaml updated to tag ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY